# Project Name
TARGET = DebugTest

# Sources
CPP_SOURCES = DebugTest.cpp b3ReadWavFile.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
USE_FATFS = 1
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
